# Fichier : .github/workflows/hugo.yml

name: Deploy Hugo site to Pages

on:
  # Se déclenche à chaque push sur la branche `main`
  push:
    branches:
      - main

  # Permet de lancer ce workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

# Autorisations pour que l'action puisse déployer sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# N'autoriser qu'un seul déploiement à la fois
concurrency:
  group: "pages"
  cancel-in-progress: true

# Variables d'environnement par défaut
defaults:
  run:
    shell: bash

jobs:
  # Tâche de construction
  build:
    runs-on: ubuntu-latest
    env:
      # --- VERSION CORRIGÉE ---
      HUGO_VERSION: 0.150.0 
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/" --ignoreBuildErrors

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Tâche de déploiement
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4